name: XML Validation

on:
  pull_request:

jobs:
  validate-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Get changed XML files in the PR
        id: get_xml_files
        run: |
          echo "Fetching changed files in the PR"
          # Get list of changed files between PR base and head branches
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.xml$' || true)
          echo "Changed XML files:"
          echo "$files"
          # Output as newline-separated string for next step
          echo "::set-output name=files::$files"

      - name: Validate changed XML files
        if: steps.get_xml_files.outputs.files != ''
        run: |
          set -e
          ERROR=0
          for file in ${{ steps.get_xml_files.outputs.files }}; do
            echo "🔍 Validating $file"
            if ! xmlstarlet val -e -s "$file"; then
              echo "❌ XML validation failed for $file"
              ERROR=1
            fi
          done

          if [ $ERROR -ne 0 ]; then
            echo "::error ::XML validation failed."
            exit 1
          else
            echo "✅ All changed XML files passed validation."
          fi

      - name: No XML changes found
        if: steps.get_xml_files.outputs.files == ''
        run: echo "No changed XML files to validate."
